# server
server:
  port: 8080

# sprig configs
spring:
  application:
    name: rentcars

  datasource:
    url: jdbc:postgresql://localhost:5432/rentcar_storage
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092

# FeignClient
#feign:
#  client:
#    address:
#      url: http://localhost:8080